### ISSUE TITLE
[ATM9 - 0.2.23] CTRL + x keybind seems to ignore CTRL and triggers on just x

### ISSUE THREAD

**Issue by Chevron9** [AllTheMods/ATM-9#881] opened 2023-11-26 14:43 UTC
For some reason, any keybind that uses CTRL seems to ignore the CTRL part and also triggers when CTRL is not pressed. 

Example: Traveler's Backpack is set to open on CTRL+1

Expect behaviour: I press 1, I select the first item in my hotbar. I press CTRL+1, I open my backpack.
Actual behaviour: I press 1, I select the first item in my hotbar AND my Backpack opens. CTRL+1 does the same thing.

This was working in .22, not sure what changed. I did notice some of my settings liek shaders were reset, so presumably something related to that.

**Comment by Queen4Eternity** [comment] 2023-11-26 16:22
I'm having the same issue with Shift. I had my wireless grid set as Shift + E and my inventory as just E. When I pressed E it would first open the wireless grid and then immediately switch to open my inventory. It was working fine up until the most recent update.

**Comment by Chevron9** [comment] 2023-11-26 16:24
If it helps, I/we was also using CTRL+E as keybind for Wireless Terminal and that also doesn't work now. I'm happy to provide logs about this if you can tell me which ones are needed.

**Comment by Wraken** [comment] 2023-11-26 21:29
Got the same here, everything bind on the same key with alt/ctrl/shift open at the same time.

**Comment by Kevin-Marsh** [comment] 2023-11-27 01:29
This is apparently a bug within forge itself.

**Comment by aAndrew3030** [comment] 2023-11-27 02:24
Has anyone tried editing the keybinds in the options.txt file directly?

**Comment by shiloh-nelson** [comment] 2023-11-27 04:06
I've been having this same issue since the most recent update

**Comment by tkuneck** [comment] 2023-11-29 03:58
Looks like this may be a bug for the forge issue:
https://github.com/MinecraftForge/MinecraftForge/issues/9806

Also looks like a fix was committed, but the issue is still there for me in forge 47.2.8 / atm9 0.2.24.

**Comment by aAndrew3030** [comment] 2023-11-29 05:00
I can also confirm it has not been fixed as of 47.2.8. FWIW the issue is not present on neoforge. It seems the only options at this point are to wait to see if forge fixes the issue, or use the previous version of the pack. The other option would be to use this current version of the pack with neoforge (but I would only recommend that if your capable of troubleshooting potential issues yourself!!!)

**Comment by LexManos** [comment] 2023-11-29 05:50
When a commit is made to 1.20.2 it doesn't automagically apply to 1.20.1.
Especially not builds hat were created before the commit happened. Please check the [changelogs](https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.1-47.2.14/forge-1.20.1-47.2.14-changelog.txt) to make sure what you think was added is in the build you try.
In this case, as you can see by the [linked commit](https://github.com/MinecraftForge/MinecraftForge/commit/b33e168969be6360bc6b962e31bcc62c5e54fe4c) and the changelog that it is in 47.2.9, and considering I batched the backports, the first build that you can download that actually has it would be 47.2.14

**Comment by tkuneck** [comment] 2023-12-01 23:49
Confirming the issue is not present in forge 47.2.14 / atm 0.2.25 for me. Thanks Lex (forge) and ATM team.

**Closed** 2024-03-16 00:28 UTC

**Comment by Shadark** [comment] 2024-07-15 13:15
Seems to be happening for me again in modpack version 0.2.61, forge 47.2.20, similar as the other issue mentioned above (even if different modpack). Forge seems to think that it's not an issue from their end for what I saw? https://github.com/MinecraftForge/MinecraftForge/issues/9806

**Comment by ajaxnotmeta** [comment] 2024-12-07 22:42
> Seems to be happening for me again in modpack version 0.2.61, forge 47.2.20, similar as the other issue mentioned above (even if different modpack). Forge seems to think that it's not an issue from their end for what I saw? [MinecraftForge/MinecraftForge#9806](https://github.com/MinecraftForge/MinecraftForge/issues/9806)

can confirm! using only Vanilla Forge, installing Sophisticated backpack as a test subject, put the backpack on chesplate slot then binds backpack into CTRL+E you get same effect just like described on that issue(and even wont hapen on that specific version also mentioned there)
