### ISSUE TITLE
Last two updates 0.2.38 and 0.2.39, create new world crash

### ISSUE THREAD

**Issue by grigoras-cristinel** [AllTheMods/ATM-9#1225] opened 2024-01-24 09:58 UTC
sgjourney error

[Render thread/INFO] Loaded 74/74 KubeJS server scripts in 0.042 s with 0 errors and 0 warnings
[24/01/2024 11:54:37 AM] [Render thread/INFO] Scripts loaded
[24/01/2024 11:54:37 AM] [Render thread/INFO] Initializing recipe event...
[24/01/2024 11:54:39 AM] > Errors in registry minecraft:root:
[24/01/2024 11:54:39 AM] >> Errors in element minecraft:worldgen/template_pool:
[24/01/2024 11:54:39 AM] java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/template_pool]: [sgjourne
[minecraft-0.2.39crash.log](https://github.com/AllTheMods/ATM-9/files/14036489/minecraft-0.2.39crash.log)
y:stargate_outpost/lantean_outpost_ocean_pool, sgjourney:stargate_pedestal/stargate_pedestal, sgjourney:stargate_pedestal/stargate_pedestal_badlands, sgjourney:stargate_pedestal/stargate_pedestal_chulak, sgjourney:stargate_pedestal/stargate_pedestal_deep_dark, sgjourney:stargate_pedestal/stargate_pedestal_desert, sgjourney:stargate_pedestal/stargate_pedestal_jungle, sgjourney:stargate_pedestal/stargate_pedestal_mushroom, sgjourney:stargate_pedestal/stargate_pedestal_snow]
[24/01/2024 11:54:39 AM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.MappedRegistry.m_203521_(MappedRegistry.java:331)
[24/01/2024 11:54:39 AM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.resources.RegistryDataLoader.m_257131_(RegistryDataLoader.java:69)
[24/01/2024 11:54:39 AM] 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[24/01/2024 11:54:39 AM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.resources.RegistryDataLoader.m_247207_(RegistryDataLoader.java:65)

[minecraft-0.2.39crash.log](https://github.com/AllTheMods/ATM-9/files/14036495/minecraft-0.2.39crash.log)

**Comment by Mitchell5200** [comment] 2024-01-24 10:34
hmm, that's the second time an instance in AT launcher has crashed on the 0.2.38/39 updates, 

Please check the config `serverconfigupdater-common.toml` in the configs folder and compare to https://github.com/AllTheMods/ATM-9/blob/main/config/serverconfigupdater-common.toml, if it does Not match, copy the config contents from Github and replace the local config,

OR, Path to `/kubejs/data/sgjourney/` and delete `worldgen`

Duplicate of #1217

**Comment by grigoras-cristinel** [comment] 2024-01-24 14:57
Thanks,

I have deleted manualy /kubejs/data/sgjourney/worldgen and is working. Serverconfigupdater is ok.

**Closed** 2024-09-28 07:02 UTC
Labels: Bug, duplicate
