### ISSUE TITLE
keepInventory: true doesn't fully work.

### ISSUE THREAD

**Issue by boramuyar** [AllTheMods/ATM-9#107] opened 2023-07-16 12:03 UTC
Steps to reproduce:
0. set gamerule `keepInventory` to `true`
1. Put some armor and weapon/tools and some other blocks in your inventory.
2. Kill yourself
3. Click on "Respawn" button.
4. When respawned, all items except the armor and weapons will dissapear.

The problem is, the items dissapear completely, there is no grave, no item drops or anything.

**Comment by MitztheKat** [comment] 2023-07-16 14:22
can confirm

**Comment by MitztheKat** [comment] 2023-07-16 15:19
Narrowed down the update that caused this to v.31 - One of the mods added likely messed with inventory & keeps only armor, weapons & tools - not hotbar.

**Comment by boramuyar** [comment] 2023-07-16 16:24
I couldn't find a solution, for now better to play keepInventory to false, tombstone keeps the inventory content. Much more reliable than keepInventory.

**Comment by Mrjinx453** [comment] 2023-07-17 09:50
IDK if the FTB utilities has been added for /back and /home etc but I added a datapack to my install from Day 1 that allows that, normally my son wont play without Keep inventory on, so when this stopped working- that was my answer :)

**Comment by aAndrew3030** [comment] 2023-07-18 02:10
The problem is caused by EnderIO and has been fixed in dev, but has not been released yet. I am sure ATM will update it as soon as it is released

**Comment by aAndrew3030** [comment] 2023-07-18 02:26
https://github.com/SleepyTrousers/EnderIO-Rewrite/issues/250

**Closed** 2024-03-16 00:18 UTC
