### ISSUE TITLE
Using AllTheOres hammers dupes items

### ISSUE THREAD

**Issue by Bucedli** [AllTheMods/ATM-9#1331] opened 2024-02-12 09:08 UTC
When I used the hammers to make ore dust the hammer instantly broke/disappeared giving one raw ore's worth of dust and duping the rest of the raw ores. Happens in inventory crafting and in crafting tables. Using latest update (0.2.45)
![2024-02-12_09 44 03](https://github.com/AllTheMods/ATM-9/assets/159765319/5633b8be-4f0c-4a8c-b466-4bdb684e6f83)
![2024-02-12_09 44 23](https://github.com/AllTheMods/ATM-9/assets/159765319/4eec13be-c736-408b-9740-a85100a6c9e2)
![2024-02-12_09 52 24](https://github.com/AllTheMods/ATM-9/assets/159765319/c38f7eb1-d7a1-4831-a1fa-c1ff98f525ed)
![2024-02-12_09 52 27](https://github.com/AllTheMods/ATM-9/assets/159765319/95afafa6-f6d1-47b0-82c8-6bc93184f65b)
![2024-02-12_09 56 17](https://github.com/AllTheMods/ATM-9/assets/159765319/f6f3e975-e70d-4b34-bec8-bcc24959ff5e)

**Comment by Mitchell5200** [comment] 2024-02-12 10:38
Duplicate of #1327, #1331, #1332, #1333, 1334
Cause is FastWorkbench, hotfix releasing soon

**Closed** 2024-02-12 13:10 UTC
Labels: bug, duplicate, mod bug, in dev
