### ISSUE TITLE
[Bug]: Sophisticated Backpack Tank upgrade pulling water from Sink even though the option is set to "Not interact with world"

### ISSUE THREAD

**Issue by Jczion** [AllTheMods/ATM-9#1697] opened 2024-05-08 23:06 UTC
### Possible Fixes

Yes

### Modpack Version

0.2.58

### What happened?

Using a Sophisticated Backpack with the "Advanced Pump" upgrade, I was standing near a Kitchen Sink from "Cooking for Blockheads". I noticed that I was absorbing water from it even though I have "Do Not Interact With World" enabled. Even setting it to "Input" makes it absorb water while near the sink

**Comment by Jmpp2909** [comment] 2024-05-08 23:28
A Sink is a infinite water tank pretty much, works the same way as a normal fluid tank
So its working as intended.

Interact with world option means it wont input/output from/as actual fluid blocks, example: set pump mode on a backpack with water to Output, and it will start placing source blocks, the opposite if set to input, it will break the source blocks around and store in the backpack as liquid

**Comment by Jczion** [comment] 2024-05-08 23:30
So without turning the tank option to off, I won't be able to walk near the sink without absorbing the water?

**Comment by Jmpp2909** [comment] 2024-05-08 23:34
![image](https://github.com/AllTheMods/ATM-9/assets/129900104/fc516a17-bc61-43bf-a879-9fa8b2289d18)
At max filter what can go be pumped in using Advanced version

**Comment by Jczion** [comment] 2024-05-08 23:35
yeah that's fair, I don't exactly need water in the tank i suppose

**Comment by Jmpp2909** [comment] 2024-05-08 23:42
Close the issue if you dont have more questions, helps with organization lol

**Closed** 2024-05-08 23:44 UTC
Labels: Bug
