### ISSUE TITLE
[Bug]: Iron Tier Upgrade Has Infinite Uses In Survival

### ISSUE THREAD

**Issue by ZilophosGH** [AllTheMods/ATM-9#1576] opened 2024-04-02 13:44 UTC
### Possible Fixes

Yes

### Modpack Version

0.2.56

### What happened?

The "Basic to Iron Tier Upgrade" item from Sophisticated Storage doesn't get consumed when you use it on a chest.

**Comment by Kevin-Marsh** [comment] 2024-04-02 22:46
This is working properly for me. What chest are you using it on specifically and do you have anything else in your inventory when you are using it such as an ae universal terminal?

**Comment by zozoroh** [comment] 2024-04-05 20:02
this is happening on single player with the basic tier upgrade for me. video here: 

https://streamable.com/i9zlqv 

.56 patch 

the basic to iron consumes the upgrade for me, however the basic is the one with the funny behavior

**Comment by James103** [comment] 2024-04-06 03:17
Are you able to reproduce this on a fresh Minecraft 1.20.1 Forge instance with Sophisticated Core and Storage (along with their dependencies) installed?

**Comment by P3pp3rF1y** [comment] 2024-04-07 16:24
This is fixed in the latest release of sophisticated storage was an issue when upgrading from vanilla chest/barrel that thrown an error and because of that didn't complete the logic where the upgrade is consumed.

**Closed** 2024-04-10 22:12 UTC
Labels: Bug
