### ISSUE TITLE
AE2 Jei sync problem[Bug]: 

### ISSUE THREAD

**Issue by K1kk0m4n** [AllTheMods/ATM-9#1565] opened 2024-03-31 12:24 UTC
### Modpack Version

All the Mods 9-0.2.55

### What happened?

AE 2 Jei sync not working again after newest update. It was fixed in All the Mods 9-0.2.53 but now the same thing is happening.

**Comment by Mitchell5200** [comment] 2024-03-31 12:34
duplicate of #1554

**Closed by Mitchell5200** 2024-03-31 12:34 UTC
Labels: Bug
