### ISSUE TITLE
Some Mystical Agriculture seeds are not available in Hopper Botany Pots

### ISSUE THREAD

**Issue by Jethrootje** [AllTheMods/ATM-9#214] opened 2023-08-09 18:54 UTC
So as far as I know the Netherite Seeds and Dark Steel Seeds can't be placed in a Hopper Botany Pot

**Comment by M4RC0Sx** [comment] 2023-08-09 19:17
Also any seed that uses mystical aggregations cruxes does not work anymore on botany pots.

**Comment by tekook** [comment] 2023-08-10 08:21
Dark steel confirmed. 
But Netherrite works fine for me

**Comment by tekook** [comment] 2023-08-10 08:22
> Also any seed that uses mystical aggregations cruxes does not work anymore on botany pots.

Nether star works fine. You have to have insanium farmland to be able to place nether start seed in botany.
Dragen Egg Seeds never worked (even in atm8)

**Comment by Jethrootje** [comment] 2023-08-10 08:24
> > Also any seed that uses mystical aggregations cruxes does not work anymore on botany pots.
> 
> Nether star works fine. You have to have insanium farmland to be able to place nether start seed in botany. Dragen Egg Seeds never worked (even in atm8)

Oh woops, wrong one, I meant Grains of Infinity Seeds

**Comment by ApostolosRisen** [comment] 2023-08-11 15:29
As far as I have tried nothing from ender io works in the botany pots

**Comment by Spacelord09** [comment] 2023-08-15 17:57
In v0.0.51 I found the following EnderIO Seeds missing a recipe for Botany Pots:
- Vibrant Alloy Seeds
- Energetic Alloy Seeds
- Pulsation Alloy Seeds
- Dark Steel Seeds
- Soularium Seeds
- Conductive Alloy Seeds
- Redstone Alloy Seeds
- Copper Alloy Seeds

#227 is a dupe of this issue.

**Comment by aAndrew3030** [comment] 2023-08-17 14:09
The seeds were added to the latest version of Botany Pots

**Comment by Spacelord09** [comment] 2023-09-04 22:27
Fixed. Please close.

**Closed** 2024-03-16 00:26 UTC
