### ISSUE TITLE
Scanner and Tablet issue

### ISSUE THREAD

**Issue by bhenjum** [AllTheMods/ATM-9#977] opened 2023-12-10 15:56 UTC
I am on the current realease *.*.2.28, The storage scanner and tablet from RFTools are not working properly. The storage scanner works flawlessly with scanning storage but the tablet with the Storage Screen Control Module does not work after setting the scanner as the entity. It will not even open the gui. The table Gui is working to place the control module but after its is socketed it does nothing.

**Comment by nailfor** [comment] 2023-12-18 00:08
I am have the same issue. I found this topic from rftool https://github.com/McJtyMods/RFToolsStorage/issues/82
[Kataiser9](https://github.com/Kataiser9) wrote that the problem is in the Botarium mod, but i dont know how to fix it

**Comment by xslugx** [comment] 2024-01-06 00:51
This problem has been resolved in the latest version of RFToolsStorage, I am submitting a pull request

**Comment by nailfor** [comment] 2024-01-07 16:20
Yep, fixed in rftools 5.0.2

**Closed** 2024-03-21 06:18 UTC
