### ISSUE TITLE
compressing blocks completely broken, allowing dupe of items

### ISSUE THREAD

**Issue by rmobis** [AllTheMods/ATM-9#1327] opened 2024-02-12 05:18 UTC
On a fresh install of 0.2.45 I'm getting very weird behavior when compacting blocks.

![image](https://github.com/AllTheMods/ATM-9/assets/2119933/2ba912cd-99d9-4af0-ade6-0dc1e8be9757)

**Steps to Reproduce:**
- Pick a stack of 64 dirt (any compressible block works)
- Open a crafting table and spread it on grid as to craft a compressed Dirt 1x block
	- You should have 7 dirt on each slot of the crafting table
- Click the output slot to remove a single Dirt 1x block
	- You should now have 12 dirt on each slot of the crafting table

If you keep taking compressed items, it will keep roughly doubling the amount on each slot of the crafting table up unti about 1.3b before it overflows and it kinda stops. If you exit the crafting table before it overflows, however, you get to dude about 10 billion of the item you were compressing.

I first noticed this because trying to compress 9 full stacks would only wield 26 or 27 compressed blocks instead of 64.

**Edit:** Downgraded to 0.2.44 and seems to be working fine.

**Comment by Mitchell5200** [comment] 2024-02-12 10:37
Duplicate of #1327, #1331, #1332, #1333, 1334
Cause is FastWorkbench, hotfix releasing soon

**Closed** 2024-02-12 13:10 UTC
Labels: bug, mod bug, in dev
